[nodejs]
format = 'via [ğŸ¤– $version](bold green) '

# Show the current directory
[directory]
truncation_length = 3

# Customize the prompt symbol
[character]
success_symbol = "[âœ”](bold green)"
error_symbol = "[âœ—](bold red)"

[git_branch]
symbol = "ğŸŒ¿ "
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_status]
conflicted = 'ğŸš©'
ahead = 'ğŸğŸ’¨ â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
staged = '[++\($count\)](green)'
deleted = 'ğŸ—‘'
