
theme = 'night_owl'

[editor]
true-color = true
mouse = false
rulers = [80]
# bufferline = "always"
line-number = "relative"
auto-save = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-signature-help-docs = true
display-inlay-hints = true

[editor.statusline]
left = ['mode', 'spinner']
center = ['file-name']
right = ['file-encoding', 'file-line-ending', 'file-type']
separator = "|"
mode.normal = 'normal'
mode.insert = 'insert'
mode.select = 'select'

[editor.indent-guides]
render = true

[keys.normal]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = {k = 'normal_mode'} # maps `jk` to exit insert mode 